title: -=流浪笔记.三丰=-
subtitle: 水唯善下方成海,山不衿高自极天， 随意记录点点滴滴……
description: 分时分段 单车 旅行 学习

# 博客是否自动生成目录，false为不生成
enableToc: true
permalink: ':title/'
#baseurl: "" # the subpath of your site, e.g. /blog
url: 'https://isanfeng.github.io' # the base hostname & protocol for your site, e.g. http://example.com
gitee_url: 'http://iwangsanfeng.gitee.io'

# Author settings add your name
author: 流浪笔记.三丰

author-pic: isanfeng.jpg
about-author: Live the life you love, Love the life you lives.
about-author-detail-0: 侠之大者，四海为家；一人一驹，浪迹天涯。<br>To be a SkyTraveler.<br>人不知道什么时候会生命停止，也许了解之后就会发现人生的意义是什么。
about-author-detail-1:

#修改成你自己的
# Contact links
website: isanfeng.github.io
linkedin: # Add your Linkedin handle
twitter: wangsf111
facebook: iwangsanfeng
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

#修改成你自己的
email: wangsf927@163.com
phone: secret
github: isanfeng
jianshu:
juejin:
csdn:

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus修改成你自己的
discus_identifier:
# Add your discus identifier

#intensedebate修改成你自己的
intensedebate_identifier: 817a70ae8b1e66f93255bb987bc33468
# 开关控制是否显示
intensedebate_comments: false

# Tracker Google Analytics修改成你自己的
google-analysis-gitee: G-LR2C328Y6Y
google-analysis-github: G-0K52Q80DV8
baidu-analysis: 42bccbe026e11e0ec8bcd67d40d41529

# Paginate
paginate: 27
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

imagepath: /assets/img/

links:
  - name:         HOME
    url:          https://isanfeng.github.io
    external:     false
  - name:         ABOUT
    url:          /about
    external:     false

#添加分类步骤：
#1：在_config.yml links1及blog_中添加对应内容
#2：在_includes里面headr.html中添加对应内容
#3：在根目录blog文件中创建对应内容并修改index文件

label1: <span style="font-size:12px">小主：
label2: </span>


links1:
  - name:         全部
    url:          /
    type:         recent
    external:     false
  - name:         分时分段环游地球
    url:          /blog/Bikepacking
    type:         Bikepacking
    external:     false
  - name:         工欲善其事
    url:          /blog/Fire
    type:         Fire
    external:     false
  - name:         必先利其器
    url:          /blog/Tools
    type:         Tools
    external:     false
  - name:         PythonStudy
    url:          /blog/Python
    type:         Python
    external:     false
  - name:         一刻
    url:          /blog/Essays
    type:         Essays
    external:     false
  - name:         八两
    url:          /blog/Reading
    type:         Reading
    external:     false

blog_1:    recent
blog_2:    Bikepacking
blog_3:    Fire
blog_4:    Tools
blog_5:    Python
blog_6:    Essays
blog_7:    Reading

#permalink: /:year/:month/:day/:title.html
