title: 流浪笔记.三丰™
subtitle: 水唯善下方成海,山不衿高自极天， 随意记录点点滴滴……
description: Bikepacking 单车 旅行 学习 Fire Python

# 博客是否自动生成目录，false为不生成
enableToc: true
permalink: ':title/'
#baseurl: "" # the subpath of your site, e.g. /blog
url: 'https://isanfeng.github.io' # the base hostname & protocol for your site, e.g. http://example.com
gitee_url: 'https://iwangsanfeng.gitee.io'

# Author settings add your name
author: 流浪笔记<i class="fa fa-bicycle" aria-hidden="true"></i>三丰

author-pic: isanfeng.jpg
about-author: Live the life you love, Love the life you lives.
about-author-detail-0: 侠之大者，四海为家；一人一驹，浪迹天涯。
about-author-detail-1:
  ☛易记一级域名☚<br>
  DN-L1-Ⅰ：<a href="https://iwangsanfeng.gitee.io">http://isanfeng.cf</a>    ▶㊟"cf"中文代表“出发”<br>
  DN-L1-Ⅱ：<a href="https://isanfeng.vercel.app">http://isanfeng.ml</a>    ▶㊟"ml"中文代表“美丽”<br>
  DN-L1-Ⅲ：<a href="https://iwangsanfeng.gitee.io">http://isanfeng.tk</a>    ▶㊟"tk"中文代表“天空”<br>
  ☛永久二级域名☚<br>
  DN-L2-Ⅰ：<a href="https://iwangsanfeng.gitee.io">https://iwangsanfeng.gitee.io</a><br>
  DN-L2-Ⅱ：<a href="https://isanfeng.vercel.app">https://isanfeng.vercel.app</a><br>
  DN-L2-Ⅲ：<a href="https://isanfeng.github.io">https://isanfeng.github.io</a><br>

#修改成你自己的
# Contact links
website: isanfeng.github.io
linkedin: # Add your Linkedin handle
twitter: wangsf111
facebook: iwangsanfeng
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

#修改成你自己的
email: wangsf927@163.com
phone: secret
github: isanfeng
gitee: iwangsanfeng
dockhub: wangsf927
jianshu:
juejin:
csdn:

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus修改成你自己的
discus_identifier:
# Add your discus identifier

#intensedebate修改成你自己的
intensedebate_identifier: 817a70ae8b1e66f93255bb987bc33468
# 开关控制是否显示
intensedebate_comments: false

# Tracker Google Analytics修改成你自己的
google-analysis-gitee: G-LR2C328Y6Y
google-analysis-github: G-0K52Q80DV8
baidu-analysis: 42bccbe026e11e0ec8bcd67d40d41529

# Paginate
paginate: 81
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

imagepath: /assets/img/

links:
  - name:         <i class="fa fa-thermometer-full"></i> 首页
    url:          /
    external:     false
  - name:         <i class="fa fa-thermometer-half"></i> 旅行地图
    url:          /travel_map
    external:     false
  - name:         <i class="fa fa-thermometer-quarter"></i> 关于
    url:          /about
    external:     false

#添分类步骤：
#1：在_config.yml links1及blog中添加对应内容
#2：在_includes里面headr.html中添加对应内容
#3：在根目录blog文件中创建对应内容并修改index文件

label1: <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
label2:


links1:
  - name:         全部
    url:          /
    type:         recent
    external:     false
  - name:         分时分段环游地球
    url:          /blog/Bikepacking
    type:         Bikepacking
    external:     false
  - name:         工欲善其事
    url:          /blog/Life
    type:         Life
    external:     false
  - name:         必先利其器
    url:          /blog/Tools
    type:         Tools
    external:     false
  - name:         自强不息
    url:          /blog/Study
    type:         Study
    external:     false
  - name:         厚德载物
    url:          /blog/Essays
    type:         Essays
    external:     false
  - name:         镜像
    url:          https://iwangsanfeng.gitee.io
    type:         site
    external:     true

blog_1:    recent
blog_2:    Bikepacking
blog_3:    Life
blog_4:    Tools
blog_5:    Study
blog_6:    Essays

#permalink: /:year/:month/:day/:title.html
