title: 流浪笔记.三丰
subtitle:
description:

# 博客是否自动生成目录，false为不生成
enableToc: true
permalink: ':title/'
#baseurl: "/adam-blog" # the subpath of your site, e.g. /blog
url: "http://isanfeng.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings add your name
author: 流浪笔记.三丰

author-pic: isanfeng.jpg
about-author: Live the life you love, Love the life you lives. To be a funny wanderer.
about-author-detail: To be a SkyTraveler.

#修改成你自己的
# Contact links
website: isanfeng.github.io
linkedin: # Add your Linkedin handle
twitter: wangsf111
facebook: iwangsanfeng
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

#修改成你自己的
email: wangsf927@163.com
phone: secret
github: isanfeng
jianshu:
juejin:
csdn:

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus修改成你自己的
discus_identifier:
# Add your discus identifier

#intensedebate修改成你自己的
intensedebate_identifier: 817a70ae8b1e66f93255bb987bc33468
intensedebate_comments: true

# Tracker Google Analytics修改成你自己的
google-analysis:
baidu-analysis: 42bccbe026e11e0ec8bcd67d40d41529

#youyan
youyan-id:

# Paginate
paginate: 27
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

imagepath: /assets/img/posts

links:
  - name:         Home
    url:          https://isanfeng.github.io
    external:     false
  - name:         About
    url:          /about
    external:     false

#添加分类步骤：
#1：在_config.yml links1及blog_中添加对应内容
#2：在_includes里面headr.html中添加对应内容
#3：在根目录blog文件中创建对应内容并修改index文件

label1: <span style="font-size:12px">撰写自：
label2: </span>


links1:
  - name:         All
    url:          /
    type:         recent
    external:     false
  - name:         Bikepacking&Hike
    url:          /blog/Bikepacking
    type:         Bikepacking
    external:     false
  - name:         Essays
    url:          /blog/Essays
    type:         Essays
    external:     false
  - name:         Reading&Moives
    url:          /blog/Reading
    type:         Reading
    external:     false
  - name:         Python
    url:          /blog/Python
    type:         Python
    external:     false
  - name:         必先利其器
    url:          /blog/Tools
    type:         Tools
    external:     false

blog_1:    recent
blog_2:    Bikepacking
blog_3:    Essays
blog_4:    Reading
blog_5:    Python
blog_6:    Tools

#permalink: /:year/:month/:day/:title.html
