#-------------------------------
# General Site Settings
title: 𝓲三丰🚵去流浪
logo: # You can add own logo. For example '/images/logo.png'.
description: <ion-icon name="chevron-back-outline"></ion-icon><ruby>侠   之   大   者，四   海   为   家<rp>(</rp><rt>xiá zhī dà zhě, sì hǎi wéi jiā</rt><rp>)</rp></ruby><ion-icon name="chevron-forward-outline"></ion-icon><br><br><ion-icon name="chevron-back-outline"></ion-icon><ruby>一   人   一   驹，浪   迹   天   涯<rp>(</rp><rt>yī rén yī jū, làng jì tiān yá</rt><rp>)</rp></ruby><ion-icon name="chevron-forward-outline"></ion-icon>
# baseurl: "/saranatheme" # The subpath of your site, e.g. /blog
url: 'https://isanfeng.github.io' # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author-name: 𝓲三丰🚴流浪

#-------------------------------
# Hero Settings
hero:
  image: '/images/banner.jpg'
  title: ༺三丰🚴笔记༻
  description: Thoughts, stories and ideas.

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com/wangsf111"}
- {icon: "ion-logo-facebook", link: "https://facebook.com/iwangsanfeng"}
- {icon: "ion-logo-twitch", link: "https://space.bilibili.com/64878769"}
- {icon: "ion-logo-github", link: "https://isanfeng.github.io"}
- {icon: "ion-logo-gitlab", link: "https://iwangsanfeng.gitee.io"}
- {icon: "ion-logo-electron", link: "https://isanfeng.vercel.app"}


# Example of adding a new link to the author section and footer - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: wangsf927@163.com # Add your email for contact form
  description: Sanara comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Sanara comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#intensedebate修改成你自己的
intensedebate_identifier: 817a70ae8b1e66f93255bb987bc33468
# 开关控制是否显示
intensedebate_comments: false

# Tracker Google Analytics修改成你自己的
google-analysis-gitee: G-LR2C328Y6Y
google-analysis-github: G-0K52Q80DV8
baidu-analysis-github: 42bccbe026e11e0ec8bcd67d40d41529
baidu-analysis-gitee: c1cc63cef10ce15edf05b9fcab36e06b


#-------------------------------
# Newsletter
mailchimp: false # To enable the mailchimp form, use the value 'true'. To disable the form, use the value 'false' or leave the field blank.
mailchimp-title: 喜欢吗？那就订阅我吧 # Add your title.
mailchimp-text: 立即订阅随时了解我的近况，我可能会定期发送旅行路线攻略、装备分析文章等信息给你喔！ # Add your description.
mailchimp-identifier: 39457248a2 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 99
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed
