name: sync2gitee
on: page_build
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:isanfeng/isanfeng.github.io.git"
          destination-repo: "git@gitee.com:iwangsanfeng/iwangsanfeng.git"
